spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode:  HTML
    cache: false
    encoding: UTF-8
    check-template-location: true
    
server:
  port : 2100
  error:
    whitelabel:
      enabled: false    
    