server:
  port: 2000

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode:  HTML
    cache: false
    encoding: UTF-8
    check-template-location: true
    
api:
  path: http://localhost:1000
  
front:
  path: http://localhost:2000